export const ADD_MOVIE = 'ADD_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const UPDATE_SUCCEEDED = 'UPDATE_SUCCEEDED';

export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';
